LangString addOrReinstall ${LANG_JAPANESE} "コンポーネントの追加/再インストール"
LangString alreadyInstalled ${LANG_JAPANESE} "インストール済み"
LangString alreadyInstalledLong ${LANG_JAPANESE} "${PRODUCTNAME} ${VERSION} はすでにインストールされています。実行する操作を選択し、次へをクリックして続行してください。"
LangString appRunning ${LANG_JAPANESE} "{{product_name}} が実行中です！先に終了してから再試行してください。"
LangString appRunningOkKill ${LANG_JAPANESE} "{{product_name}} が実行中です！$\nOKをクリックして強制終了します"
LangString chooseMaintenanceOption ${LANG_JAPANESE} "実行するメンテナンス操作を選択してください。"
LangString choowHowToInstall ${LANG_JAPANESE} "${PRODUCTNAME} のインストール方法を選択してください。"
LangString createDesktop ${LANG_JAPANESE} "デスクトップにショートカットを作成する"
LangString dontUninstall ${LANG_JAPANESE} "アンインストールしない"
LangString dontUninstallDowngrade ${LANG_JAPANESE} "アンインストールしない（このインストーラーではアンインストールなしのダウングレードは無効です）"
LangString failedToKillApp ${LANG_JAPANESE} "{{product_name}} の強制終了に失敗しました。先に終了してから再試行してください"
LangString installingWebview2 ${LANG_JAPANESE} "WebView2 をインストール中..."
LangString newerVersionInstalled ${LANG_JAPANESE} "${PRODUCTNAME} の新しいバージョンがすでにインストールされています！古いバージョンのインストールは推奨されません。どうしても古いバージョンをインストールする場合は、先に現在のバージョンをアンインストールしてください。実行する操作を選択し、次へをクリックして続行してください。"
LangString older ${LANG_JAPANESE} "古い"
LangString olderOrUnknownVersionInstalled ${LANG_JAPANESE} "システムに ${PRODUCTNAME} の $R4 バージョンがインストールされています。インストール前に現在のバージョンをアンインストールすることをお勧めします。実行する操作を選択し、次へをクリックして続行してください。"
LangString silentDowngrades ${LANG_JAPANESE} "このインストーラーではダウングレードが無効です。サイレントインストーラーでは続行できません。グラフィカルインターフェースのインストーラーを使用してください。$\n"
LangString unableToUninstall ${LANG_JAPANESE} "アンインストールできません！"
LangString uninstallApp ${LANG_JAPANESE} "${PRODUCTNAME} をアンインストール"
LangString uninstallBeforeInstalling ${LANG_JAPANESE} "インストール前にアンインストール"
LangString unknown ${LANG_JAPANESE} "不明"
LangString webview2AbortError ${LANG_JAPANESE} "WebView2 のインストールに失敗しました！アプリは WebView2 なしでは動作できません。インストーラーを再起動してください。"
LangString webview2DownloadError ${LANG_JAPANESE} "エラー: WebView2 のダウンロードに失敗しました - $0"
LangString webview2DownloadSuccess ${LANG_JAPANESE} "WebView2 ブートストラッパーのダウンロードに成功しました"
LangString webview2Downloading ${LANG_JAPANESE} "WebView2 ブートストラッパーをダウンロード中..."
LangString webview2InstallError ${LANG_JAPANESE} "エラー: WebView2 のインストールが終了コード $1 で失敗しました"
LangString webview2InstallSuccess ${LANG_JAPANESE} "WebView2 のインストールに成功しました"
LangString deleteAppData ${LANG_JAPANESE} "アプリケーションデータを削除する"
